services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr_split
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${SONARR_TV_VOLUME}:/data
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    restart: unless-stopped