  services:
    qbittorrent:
      extends:
        file: ../service.compose.yaml
        service: arr-service
      image: lscr.io/linuxserver/qbittorrent:latest
      container_name: qbittorrent
      environment:
        - WEBUI_PORT=8085
        # - TORRENTING_PORT=6881
      volumes:
        - ./config:/config
        - ${DOWNLOAD_TORRENT_PATH}:/downloads
        - ${MEDIA_BASE_PATH}:/media/arr
        - ${LOGS_BASE_PATH}/qbittorrent:/config/qBittorrent/logs
      # healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      #   test: "curl -sf ${HEALTH_CHECK_URL}  || exit 1"
      #   interval: 1m
      #   timeout: 10s
      #   retries: 1
      depends_on:
        gluetun:
          condition: service_healthy
          restart: true
      restart: always