services:
  pinchflat:
    extends:
      file: ../service.compose.yaml
      service: arr-service
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat_split
    environment:
      - BASIC_AUTH_USERNAME=${PINCHFLAT_AUTH_USER}
      - BASIC_AUTH_PASSWORD${PINCHFLAT_AUTH_PASS}
    volumes:
      - ./config:/config
      - ${DOWNLOAD_YOUTUBE_PATH}:/downloads
      - ${LOGS_BASE_PATH}/pinchflat:/config/logs
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    restart: unless-stopped