services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat_split
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - BASIC_AUTH_USERNAME=${PINCHFLAT_AUTH_USER}
      - BASIC_AUTH_PASSWORD${PINCHFLAT_AUTH_PASS}
    volumes:
      - ./config:/config
      - ${PINCHFLAT_DOWNLOADS}:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    restart: unless-stopped