services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage_split
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    restart: unless-stopped
