services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin_split
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ./.cache:/cache
      - ${JELLYFIN_MOVIES_VOLUME}:/Films
      - ${JELLYFIN_TV_VOLUME}:/TVShows
    restart: unless-stopped