services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr_split
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${DATA_PATH}/music:/music
      - ${DATA_PATH}/downloads/music:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    restart: unless-stopped