services:
  gluetun:
      # env_file:
      # - ./.env
      environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - UPDATER_PERIOD=${UPDATER_PERIOD}
      - SERVER_COUNTRIES=${SERVER_REGIONS}