---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

# - Arr:
    # - Prowlarr:
    #     icon: prowlarr.png
    #     href: http://192.168.68.110:9696
    #     description: 
    #     showStats: true
    #     statusStyle: "dot"

    # - Radarr:
    #     icon: radarr.png
    #     href: http://192.168.68.110:7878
    #     description: 

    # - Sonarr:
    #     icon: sonarr.png
    #     href: http://192.168.68.110:8989
    #     description: 

    # - Lidarr:
    #     icon: lidarr.png
    #     href: http://192.168.68.110:8686
    #     description: Music collection manager for Usenet and BitTorrent users. 

    # - Bazarr:
    #     icon: bazarr.png
    #     href: http://192.168.68.110:6767
    #     description:
    
    # - Mylar:
    #     icon: mylar.png
    #     href: http://192.168.68.110:8090
    #     description: Comic Book downloader
    


# - Media:
    # - Jellyfin:
    #     icon: jellyfin.png
    #     href: http://192.168.68.110:8096
    #     description: 
    
    # - Jellyseerr:
    #     icon: jellyseerr.png
    #     href: http://192.168.68.110:5055
    #     description: 

    # - Kavita:
    #     icon: kavita.png
    #     # container: kavita_split
    #     href: http://192.168.68.110:5000
    #     description: Reading Server

    # - Pinchflat:
    #     icon: pinchflat.png
    #     href: http://192.168.68.110:8945
    #     description:

# - Utils:
    # - qbittorrent:
    #     icon: qbittorrent.png
    #     href: http://192.168.68.110:8085
    #     description: 

    # - Jackett:
    #     icon: jackett.png
    #     href: http://192.168.68.110:9117
    #     description: API Support for your favorite torrent trackers

    # - SABnzbd:
    #     icon: sabnzbd.png
    #     href: http://192.168.68.110:8080
    #     description: The free and easy binary newsreader
    #     showStats: true
    #     statusStyle: "dot"
    #     # siteMonitor: http://192.168.68.110:8080
    #     # server: servarr-split
    #     # container: sabnzbd_split