---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Arr:
    - Prowlarr:
        icon: prowlarr.png
        href: http://localhost:9696
        description: The Ultimate Indexer Manager.

    - Radarr:
        icon: radarr.png
        href: http://localhost:7878
        description: See all your upcoming movies in one convenient location. 

    - Sonarr:
        icon: sonarr.png
        href: http://localhost:8989
        description: Internet PVR for Usenet and Torrents. 

    - Lidarr:
        icon: lidarr.png
        href: http://localhost:8686
        description: Music collection manager for Usenet and BitTorrent users. 

    - Bazarr:
        icon: bazarr.png
        href: http://localhost:6767
        description: companion application to Sonarr and Radarr that manages and downloads subtitles based on your requirements.
    
    - Mylar:
        icon: mylar.png
        href: http://localhost:8090
        description: Comic Book downloader
    


- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://localhost:8096
        description: Media solution that puts you in control of your media. Stream to any device from your own server, with no strings attached.
    
    - Jellyseerr:
        icon: jellyseerr.png
        href: http://localhost:5055
        description: Manage requests for your media library

    - Kavita:
        icon: kavita.png
        # container: kavita_split
        href: http://localhost:5000
        description: Reading Server

    - Pinchflat:
        icon: pinchflat.png
        href: http://localhost:8945
        description: Your next YouTube media manager

- Utils:
    - qbittorrent:
        icon: qbittorrent.png
        href: http://localhost:8085
        description: an open-source software alternative to µTorrent.

    - Jackett:
        icon: jackett.png
        href: http://localhost:9117
        description: API Support for your favorite torrent trackers

    - SABnzbd:
        icon: sabnzbd.png
        href: http://localhost:8080
        description: The free and easy binary newsreader
