---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

headerStyle: boxed
color: zinc

# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey
